apiVersion: v1
kind: Pod
metadata:
  labels:
    run: jvm-usecases
    name: jvm-usecases
    internalVersion: 0.0.1
  name: jvm-usecases
spec:
  shareProcessNamespace: true
  containers:
  - image: pamir/jvm-cases:0.0.1
    imagePullPolicy: IfNotPresent
    name: jvm-usecases
    args:
      - InfiniteWait
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    resources: {}
  - image: adriantodt/alpine-zlib-jattach
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    name: jattach
    resources: {}
    securityContext:
      privileged: true

   
  dnsPolicy: ClusterFirst
  restartPolicy: Never